sources:
  - name: Clearinghouse
    handler:
      graphql:
        # For local schema updates
        #        endpoint: '{context.endpoint:http://localhost:8000/subgraphs/name/vertex-clearinghouse-subgraph}'
        # Default to hosted versions
        strategy: highestValue
        strategyConfig:
          selectionSet: |
            {
              _meta {
                block {
                  number
                }
              }
            }
          value: '_meta.block.number'
        sources:
          - endpoint: '{context.slimEndpoint:https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli-slim}'
          - endpoint: '{context.endpoint:https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli}'
    transforms:
      #      - autoTypeMerging: true
      # https://github.com/graphprotocol/graph-client
      - autoPagination:
          validateSchema: true
      - blockTracking:
          validateSchema: true
          # Ignore the fields that you don't want to be tracked
          ignoreFieldNames: []
          # Exclude the operation with the following names
          ignoreOperationNames: []
#  - name: ClearinghouseSlim
#    handler:
#      graphql:
#        endpoint: 'https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli-slim'
#    transforms:
#      - autoTypeMerging: true
documents:
  - ./src/graphql/**/*.graphql

codegen:
  contextType: 'MeshContext & { endpoint: string }'