sources:
  - name: VertexCore
    handler:
      graphql:
        # For local schema updates
        endpoint: '{context.coreEndpoint:http://localhost:8000/subgraphs/name/vertex-subgraphs-core}'
        # Default to hosted version
        # endpoint: '{context.coreEndpoint:https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli-core}'
    transforms:
      - autoPagination:
          validateSchema: true
      - blockTracking:
          validateSchema: true
          # Ignore the fields that you don't want to be tracked
          ignoreFieldNames: []
          # Exclude the operation with the following names
          ignoreOperationNames: []
      - autoTypeMerging: true
  - name: VertexMarkets
    handler:
      graphql:
        endpoint: '{context.marketsEndpoint:http://localhost:8000/subgraphs/name/vertex-subgraphs-markets}'
        # endpoint: '{context.marketsEndpoint:https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli-markets}'
    transforms:
      - autoPagination:
          validateSchema: true
      - blockTracking:
          validateSchema: true
          # Ignore the fields that you don't want to be tracked
          ignoreFieldNames: []
          # Exclude the operation with the following names
          ignoreOperationNames: []
      - autoTypeMerging: true
  - name: VertexCandlesticks
    handler:
      graphql:
        endpoint: '{context.candlesticksEndpoint:http://localhost:8000/subgraphs/name/vertex-subgraphs-candlesticks}'
        # endpoint: '{context.candlesticksEndpoint:https://api.thegraph.com/subgraphs/name/vertex-protocol/vertex-goerli-candlesticks}'
    transforms:
      - autoPagination:
          validateSchema: true
      - blockTracking:
          validateSchema: true
          # Ignore the fields that you don't want to be tracked
          ignoreFieldNames: []
          # Exclude the operation with the following names
          ignoreOperationNames: []
      - autoTypeMerging: true

documents:
  - ./src/graphql/**/*.graphql

codegen:
  contextType: 'MeshContext & { coreEndpoint: string; marketsEndpoint: string; candlesticksEndpoint: string }'